export {default as LeftPanel} from './Dashboard/LeftPanel/LeftPanel'
export {default as MainPanel} from './Dashboard/MainPanel/MainPanel'
export {default as RightPanel} from './Dashboard/RightPanel/RightPanel'
export {default as DashboardComponent} from './Dashboard/DashboardComponent'
export {default as HeaderForMobile} from './HeaderForMobile/HeaderForMobile'
export {default as MenuForMobile} from './MenuForMobile/MenuForMobile'